//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecttour.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tour_dulichEntities : DbContext
    {
        public tour_dulichEntities()
            : base("name=tour_dulichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tour_chiphi> tour_chiphi { get; set; }
        public virtual DbSet<tour_chitiet> tour_chitiet { get; set; }
        public virtual DbSet<tour_diadiem> tour_diadiem { get; set; }
        public virtual DbSet<tour_doan> tour_doan { get; set; }
        public virtual DbSet<tour_gia> tour_gia { get; set; }
        public virtual DbSet<tour_khachhang> tour_khachhang { get; set; }
        public virtual DbSet<tour_loai> tour_loai { get; set; }
        public virtual DbSet<tour_loaichiphii> tour_loaichiphii { get; set; }
        public virtual DbSet<tour_nguoidi> tour_nguoidi { get; set; }
        public virtual DbSet<tour_nhanvien> tour_nhanvien { get; set; }
        public virtual DbSet<tour> tours { get; set; }
    }
}
