//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecttour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_gia
    {
        public int gia_id { get; set; }
        public Nullable<decimal> gia_sotien { get; set; }
        public Nullable<System.DateTime> gia_tungay { get; set; }
        public Nullable<System.DateTime> gia_denngay { get; set; }
        public Nullable<int> tour_id { get; set; }
    }
}
