//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecttour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_doan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tour_doan()
        {
            this.tour_nguoidi = new HashSet<tour_nguoidi>();
            this.tour_chiphi = new HashSet<tour_chiphi>();
        }
    
        public int doan_id { get; set; }
        public int tour_id { get; set; }
        public string doan_name { get; set; }
        public Nullable<System.DateTime> doan_ngaydi { get; set; }
        public Nullable<System.DateTime> doan_ngayve { get; set; }
        public string doan_chitietchuongtrinh { get; set; }
        public Nullable<int> id_gia_tour { get; set; }
    
        public virtual tour tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour_nguoidi> tour_nguoidi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour_chiphi> tour_chiphi { get; set; }
    }
}
