//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecttour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_khachhang
    {
        public int kh_id { get; set; }
        public string kh_ten { get; set; }
        public string kh_sdt { get; set; }
        public Nullable<System.DateTime> kh_ngaysinh { get; set; }
        public string kh_email { get; set; }
        public string kh_cmnd { get; set; }
    }
}
