//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecttour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tour()
        {
            this.tour_chitiet = new HashSet<tour_chitiet>();
            this.tour_doan = new HashSet<tour_doan>();
        }
    
        public int tour_id { get; set; }
        public string tour_ten { get; set; }
        public string tour_mota { get; set; }
        public int loai_id { get; set; }
        public string block { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour_chitiet> tour_chitiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour_doan> tour_doan { get; set; }
        public virtual tour_loai tour_loai { get; set; }
    }
}
